#
# Basic settings.
#
url: http://mattgreensmith.net
baseurl: ""
title: Matt Greensmith
description: "Toolsmith, infrastructure developer, operations engineer, linux sysadmin."
avatar: /assets/images/mg_headshot.jpg

#
# Icons
#
icons:
  rss: true
  email: matt@mattgreensmith.net
  github: mgreensmith
  bitbucket:
  twitter: mgreensmith
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: https://www.linkedin.com/in/mattgreensmith
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-37160248-1
disqus: mattgreensmith

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: http://mattgreensmith.net/assets/images/mg_headshot.jpg
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - .rbenv-gemsets
